"""Initial Migration

Revision ID: 6d4c48f902f9
Revises: 
Create Date: 2024-06-13 12:19:46.584373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4c48f902f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moron', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moron_level', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moron', schema=None) as batch_op:
        batch_op.drop_column('moron_level')

    # ### end Alembic commands ###
